      * ***************************************************************
      * Created: May 9, 2016 4:57:57 PM America/New_York
      * Generated by: IBM Rational Developer for System z
      * ***************************************************************
       01 MENUI.
          02 FILLER                    PIC X(12).
      *
          02 COUNTERL                  PIC S9(4) COMP.
          02 COUNTERF                  PIC X.
          02 FILLER          REDEFINES COUNTERF.
             03 COUNTERA               PIC X.
          02 FILLER                    PIC X(2).
          02 COUNTERI                  PIC 9(4).
      * *******************************************
       01 MENUO REDEFINES MENUI.
          02 FILLER                    PIC X(12).
      *
          02 FILLER                    PIC X(3).
          02 COUNTERC                  PIC X.
          02 COUNTERH                  PIC X.
          02 COUNTERO                  PIC 9(4).